### ISSUE TITLE
Error with small time windows

### ISSUE THREAD

**Issue by olamb245** [amiezzi/narrow_band_least_squares#2]
I get the following error message when use a 10 s window for the highest frequency band: `ZeroDivisionError: division by zero` (For the record, this is on data recorded at 100 sps). I don't get the same error message if I set the window at 20 s. 

The message comes from line 43 in narrow_band_least_squares.py, specifically the `its = np.arange(0,npts,sampinc)` command. I think the issue is related to how `sampinc` is defined on line 41, where the `int()` command will round values down to 0 if the input is very small. 

I found a fix by modifying that block of code to the following:

`Fs = st[0].stats.sampling_rate`
   ` max_WINLEN = WINLEN_list[-1]`
    `sampinc = int((1-WINOVER)*(max_WINLEN*Fs))`
    `npts = len(st[0].data)`
    `its = np.arange(0,npts,sampinc)`
    `nits = len(its)-1`
    `vector_len = int(nits)`

Let me know if this is a genuine bug, or if I'm setting my window lengths too small for the highest frequency band.

**Comment by jwbishop** [comment]
@olamb245 Is this still an issue?

**Comment by olamb245** [comment]
Hi @jwbishop Sorry for the really delayed response. I forgot about this issue until I started using this package again today. The same issue I described before came up again and the fix I wrote above seemed to resolve the issue. It looks like how `sampinc` is defined is still the problem.
